name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag samin-kotisivu:latest
      
      - name: Save Docker image as a tarball
        run: docker save samin-kotisivu:latest -o image.tar
    
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar